name: "Style check"
description: "Style check using clang-format"

runs:
  using: "composite"
  steps:
    - name: "Run clang-format"
      shell: bash
      run: |
        # We only make check, not changes
        # Use the find command with the variable
        # Hint! Copy this code and store it in a script file, to run locally. Change -n by -i to apply the changes.
        PROJECT_PATH=$(pwd)

        SOURCE_FILES=$(find $PROJECT_PATH/src -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \) | tr "\n" " ")
        SOURCE_FILES+=$(find $PROJECT_PATH/include -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" -or -name "*.c" \) | tr "\n" " ")

        ERROR_FILE_FLAG=$PROJECT_PATH/clang-format_errors.txt

        CLANG_COMMAND=$(clang-format -n $SOURCE_FILES) > ${ERROR_FILE_FLAG}

        echo "Running: clang-format -n $SOURCE_FILES"

        if [ -s $ERROR_FILE_FLAG ]; then
            echo "Error: There are some files that are not formatted correctly"
            exit 1
        else
            echo "All files are formatted correctly. Niiiceee"
            exit 0
        fi

    # Upload errors as an artifact, when failed
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: Clang-format errors!!!
        path: $PROJECT_PATH/clang-format_errors.txt
        retention-days: 1
