name: "Build"
description: "Executes a compilation."

runs:
  using: "composite"
  steps:
      - name: Compile
        shell: bash
        run: |
          SRC_FOLDER=$(pwd)/src

          mkdir -p build && cd build
          cmake -DENABLE_CJSON_TEST=OFF -DRUN_COVERAGE=1 .. && make -j2

          echo "Running command: cmake -DENABLE_CJSON_TEST=OFF -DRUN_COVERAGE=1 .. && make -j2"
